name: Publish to npm

on:
  push:
    tags:
      - "v*"

jobs:
  publish:
    runs-on: ubuntu-latest
    environment: publish
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        with:
          version: 9

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: "https://registry.npmjs.org"

      - run: pnpm install --frozen-lockfile

      - run: pnpm build

      - name: Publish to NPM
        run: |
          set -euxo pipefail
          VERSION=$(node -p "require('./package.json').version")
          if echo "$VERSION" | grep -q "beta"; then
            NPM_TAG="beta"
          else
            NPM_TAG="latest"
          fi
          echo "Publishing $VERSION with $NPM_TAG tag."
          npm publish --provenance --access public --tag $NPM_TAG
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
